spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}




logging:
  pattern:
    console: "%msg%n"
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
#    com.netflix.eureka: DEBUG
#    com.netflix.discovery: DEBUG
#
